### ISSUE TITLE
源码

### ISSUE THREAD

**Issue by 474903784** [th3ee9ine/go-redis-bigkv#1]
能否提供源码给我们自行编译？
这样直接给二进制文件不敢用...

**Comment by th3ee9ine** [comment]
当然可以，功能其实比较简单，晚点我会发布git，请关注

**Comment by th3ee9ine** [comment]
> 能否提供源码给我们自行编译？ 这样直接给二进制文件不敢用...

当然可以，功能其实比较简单，晚点我会发布git，请关注
